
@host = http://localhost:3000

### Practica 7 - Miembros

### 1. Listar miembros  ->  200 con los tres del seed
GET {{host}}/miembros


### 2. Buscar el miembro 1  ->  200
GET {{host}}/miembros/1


### 3. Buscar un miembro que no existe  ->  404
GET {{host}}/miembros/99


### 4. Crear un miembro  ->  201 (activo: true por defecto)
POST {{host}}/miembros
Content-Type: application/json

{ "nombre": "Lucía Torres", "correo": "lucia@example.com", "membresia": "anual" }


### 5. Actualizar el miembro 3  ->  200
PUT {{host}}/miembros/3
Content-Type: application/json

{ "membresia": "anual", "activo": true }


### 6. Actualizar un miembro que no existe  ->  404
PUT {{host}}/miembros/99
Content-Type: application/json

{ "nombre": "Nadie" }


### 7. Eliminar el miembro 2  ->  200
DELETE {{host}}/miembros/2


### 8. Eliminar otra vez  ->  404
DELETE {{host}}/miembros/2


### 9. Inscripciones sigue respondiendo igual  ->  200
GET {{host}}/inscripciones